### ISSUE TITLE
Update fetchPostsMtc.js

### ISSUE THREAD

**Issue by jeffreyleblanc225** [brandonhellman/hit-notifier#1]
Can we replace code in fetchPostsMtc.js

`const lastPageHref = latestThread.querySelector('.structItem-pageJump > a:last-of-type').href;`

with:

`let pageJump = latestThread.querySelector('.structItem-pageJump');
  let lastPageHref = "";
  if (pageJump != null){
    lastPageHref = latestThread.querySelector('.structItem-pageJump > a:last-of-type').href;
  }
  else {  
    lastPageHref = latestThread.querySelector('.structItem-title > a').href;
  }`

This is needed for times when there is only one page, and no structItem-pageJump elements exist. Instead we can get the link from .structItem-title.

Edit:
Submitted a PR

**Comment by brandonhellman** [comment]
Close by #2
